export interface MissionPayload {
  name: string;
  fullName: string;
  description: string;
  institution?: string;
}

export interface MissionTrajectoryStep {
  label: string;
  sublabel: string;
  status: "completed" | "in-progress" | "planned";
}

export interface Mission {
  id: string;
  name: string;
  tagline: string;
  category: "lunar" | "solar" | "human-spaceflight" | "earth-observation" | "planetary" | "astrophysics" | "tech-demo";
  categoryLabel: string;
  status: "Operational" | "Mission Complete" | "Under Development" | "Flight Validated";
  statusType: "success" | "active" | "development";
  launchDate: string;
  destination: string;
  launchVehicle: string;
  orbitCoordinates?: string;
  shortDescription: string;
  fullOverview: string;
  primaryObjectives: string[];
  keyHighlights: { label: string; value: string }[];
  payloads: MissionPayload[];
  trajectory: {
    type: "lunar-descent" | "l1-halo" | "leo-human" | "mars-insertion" | "leo-docking" | "leo-radar";
    steps: MissionTrajectoryStep[];
    conceptualNotes: string;
  };
  featured: boolean;
  accentColor: string;
  imageUrl: string;
}

export const MISSIONS_DATA: Mission[] = [
  {
    id: "chandrayaan-3",
    name: "Chandrayaan-3",
    tagline: "Historic Lunar South Pole Soft Landing & In-Situ Surface Science",
    category: "lunar",
    categoryLabel: "Lunar Exploration",
    status: "Mission Complete",
    statusType: "success",
    launchDate: "14 July 2023",
    destination: "Moon, Lunar South Pole (Shiv Shakti Point - 69.373° S, 32.319° E)",
    launchVehicle: "LVM3 M4",
    orbitCoordinates: "69.373° S, 32.319° E",
    imageUrl: "/images/chandrayaan3.jpg",
    shortDescription:
      "Demonstrated end-to-end soft landing on the lunar south polar region, in-situ chemical analysis with the Pragyan rover, and high-precision descent navigation.",
    fullOverview:
      "Chandrayaan-3 is a follow-on mission to Chandrayaan-2 comprising a Lander module (Vikram) and a Rover (Pragyan), propelled to lunar orbit by a Propulsion Module. On August 23, 2023, the Vikram lander achieved a historic soft landing near the lunar south pole, making India the 4th nation to soft-land on the Moon and the 1st to land in the southern polar region.",
    primaryObjectives: [
      "Demonstrate safe and soft landing on the lunar high-latitude surface.",
      "Demonstrate rover roving operations on the Moon's regolith terrain.",
      "Conduct in-situ scientific experiments on lunar topsoil and thermal gradients."
    ],
    keyHighlights: [
      { label: "Landing Coordinates", value: "69.373° S, 32.319° E (Shiv Shakti Point)" },
      { label: "Landing Date & Time", value: "23 August 2023 at 18:04 IST" },
      { label: "Lander Mass", value: "1749.86 kg (with Rover 26 kg)" },
      { label: "Propulsion Module Mass", value: "2145.01 kg" },
      { label: "Mission Life", value: "1 Lunar Day (~14 Earth Days)" },
      { label: "Launch Mass Total", value: "3895 kg" }
    ],
    payloads: [
      {
        name: "ChaSTE",
        fullName: "Chandra's Surface Thermophysical Experiment",
        description: "Measures the vertical thermal conductivity and temperature gradient profile of lunar regolith up to a depth of 10 cm using 10 high-precision temperature sensors.",
        institution: "SPL / VSSC, Thiruvananthapuram"
      },
      {
        name: "RAMBHA-LP",
        fullName: "Radio Anatomy of Moon Bound Hypersensitive ionosphere and Atmosphere - Langmuir Probe",
        description: "Measures the near-surface lunar plasma density and its temporal variations under solar illumination.",
        institution: "SPL / VSSC, Thiruvananthapuram"
      },
      {
        name: "ILSA",
        fullName: "Instrument for Lunar Seismic Activity",
        description: "Measures lunar seismicity around the landing site and records vibrations generated by rover movements and micrometeoroid impacts.",
        institution: "LEOS / URSC, Bengaluru"
      },
      {
        name: "LIBS",
        fullName: "Laser-Induced Breakdown Spectroscope",
        description: "Emits high-energy laser pulses onto lunar rocks and soil to determine qualitative and quantitative elemental composition, confirming in-situ presence of Sulphur (S).",
        institution: "LEOS / URSC, Bengaluru"
      },
      {
        name: "APXS",
        fullName: "Alpha Particle X-Ray Spectrometer",
        description: "Irradiates soil samples with radioactive sources to detect major rock-forming elements including Al, Si, Ca, and Fe.",
        institution: "PRL, Ahmedabad"
      },
      {
        name: "SHAPE",
        fullName: "Spectro-polarimetry of HAbitable Planet Earth",
        description: "Operates from the Propulsion Module in lunar orbit to study Earth as an exoplanet candidate through spectro-polarimetric signatures in near-infrared.",
        institution: "URSC, Bengaluru"
      }
    ],
    trajectory: {
      type: "lunar-descent",
      steps: [
        { label: "Earth-Bound Manoeuvres", sublabel: "5 orbit-raising burns reaching 127,609 km apogee", status: "completed" },
        { label: "Trans-Lunar Injection (TLI)", sublabel: "Burn on Aug 1 inserting spacecraft into lunar transfer ellipse", status: "completed" },
        { label: "Lunar Orbit Insertion (LOI)", sublabel: "Retro-firing on Aug 5 capturing into 164 x 18,074 km orbit", status: "completed" },
        { label: "Powered Descent & Touchdown", sublabel: "Autonomous 4-stage brake to 69.373° S at 18:04 IST", status: "completed" }
      ],
      conceptualNotes: "Visualisation of the 40-day trajectory from Satish Dhawan Space Centre launch to Shiv Shakti Point landing."
    },
    featured: true,
    accentColor: "#E65C00"
  },
  {
    id: "aditya-l1",
    name: "Aditya-L1",
    tagline: "India's Premier Solar Observatory at Sun-Earth Lagrange Point 1",
    category: "solar",
    categoryLabel: "Solar Physics & Space Weather",
    status: "Operational",
    statusType: "active",
    launchDate: "02 September 2023",
    destination: "Halo Orbit at Sun-Earth L1 (1.5 Million km from Earth)",
    launchVehicle: "PSLV-C57 (XL Configuration)",
    orbitCoordinates: "L1 Halo Orbit (Station-keeping ~1.5M km sunward)",
    imageUrl: "/images/aditya-l1.jpg",
    shortDescription:
      "Positioned in a halo orbit around the Sun-Earth L1 point with an uninterrupted view of the Sun without occultation or eclipses.",
    fullOverview:
      "Aditya-L1 is India's first dedicated space observatory dedicated to solar physics. Positioned 1.5 million km from Earth, it carries seven indigenous scientific payloads to study solar corona dynamics, coronal mass ejections (CMEs), chromosphere flare physics, interplanetary magnetic fields, and solar wind particle acceleration.",
    primaryObjectives: [
      "Study Solar upper atmospheric (chromosphere and corona) dynamics.",
      "Observe physical processes of coronal heating and initiation of Coronal Mass Ejections (CMEs).",
      "Perform in-situ particle and plasma measurements for space weather forecasting."
    ],
    keyHighlights: [
      { label: "Orbital Vantage", value: "Sun-Earth Lagrange Point 1 (L1)" },
      { label: "Halo Orbit Insertion", value: "06 January 2024" },
      { label: "Distance from Earth", value: "1.5 Million Kilometres" },
      { label: "Payload Suite", value: "7 Scientific Payloads (4 Remote, 3 In-Situ)" },
      { label: "Spacecraft Mass", value: "1472 kg Lift-off Mass" },
      { label: "Designed Mission Life", value: "5+ Years Continuous Observation" }
    ],
    payloads: [
      {
        name: "VELC",
        fullName: "Visible Emission Line Coronagraph",
        description: "Primary payload imaging the solar corona in visible and infrared wavelengths from 1.05 to 3 solar radii.",
        institution: "IIA, Bengaluru"
      },
      {
        name: "SUIT",
        fullName: "Solar Ultraviolet Imaging Telescope",
        description: "Full-disk ultra-violet imaging of the solar photosphere and chromosphere in 200-400 nm wavelength range.",
        institution: "IUCAA, Pune"
      },
      {
        name: "ASPEX",
        fullName: "Aditya Solar wind Particle Experiment",
        description: "Measures solar wind ion composition, proton energy distribution, and suprathermal particles.",
        institution: "PRL, Ahmedabad"
      },
      {
        name: "PAPA",
        fullName: "Plasma Analyser Package for Aditya",
        description: "Continuous in-situ monitoring of solar wind electrons and heavy ions.",
        institution: "SPL / VSSC, Thiruvananthapuram"
      },
      {
        name: "SoLEXS",
        fullName: "Solar Low Energy X-ray Spectrometer",
        description: "Monitors soft X-ray solar flares to understand flare acceleration mechanisms.",
        institution: "URSC, Bengaluru"
      },
      {
        name: "HEL1OS",
        fullName: "High Energy L1 Orbiting X-ray Spectrometer",
        description: "Hard X-ray spectrometer studying non-thermal impulsive coronal flare energy.",
        institution: "URSC, Bengaluru"
      },
      {
        name: "MAG",
        fullName: "Magnetometer Suite",
        description: "Dual tri-axial fluxgate magnetometers on a 6-metre boom measuring interplanetary magnetic field vectors.",
        institution: "LEOS, Bengaluru"
      }
    ],
    trajectory: {
      type: "l1-halo",
      steps: [
        { label: "Launch by PSLV-C57", sublabel: "Placed into 235 x 19,500 km elliptical orbit", status: "completed" },
        { label: "Earth-Bound Burns", sublabel: "Series of 5 thruster firings raising apogee to deep space", status: "completed" },
        { label: "Cruise Phase to L1", sublabel: "110-day ballistic transfer trajectory toward Lagrange Point", status: "completed" },
        { label: "Halo Orbit Insertion", sublabel: "Manoeuvre on Jan 6, 2024 locking into periodic L1 orbit", status: "completed" }
      ],
      conceptualNotes: "1.5 million km journey to the gravitational equilibrium point with unobstructed 24/7 solar visibility."
    },
    featured: true,
    accentColor: "#E65C00"
  },
  {
    id: "gaganyaan",
    name: "Gaganyaan",
    tagline: "India's Sovereign Human Spaceflight Programme (HSP)",
    category: "human-spaceflight",
    categoryLabel: "Human Spaceflight",
    status: "Under Development",
    statusType: "development",
    launchDate: "2025 (Uncrewed G1 / G2) • 2026 (Crewed H1)",
    destination: "400 km Circular Low Earth Orbit (LEO)",
    launchVehicle: "Human-Rated LVM3 (HLVM3)",
    orbitCoordinates: "400 km Circular LEO at 51.6° Inclination",
    imageUrl: "/images/gaganyaan.jpg",
    shortDescription:
      "Demonstrating indigenous capability to loft a crew of 3 to a 400 km orbit for 3 days and return them safely to Indian waters.",
    fullOverview:
      "Gaganyaan is India's flagship human spaceflight initiative led by the Human Space Flight Centre (HSFC). The mission architecture encompasses a pressurized habitable Crew Module (CM), an unpressurized Service Module (SM) equipped with unified bipropellant propulsion, a solid-propellant Crew Escape System (CES), and human-rated launch vehicle systems.",
    primaryObjectives: [
      "Develop and qualify an indigenous, human-rated launch vehicle (HLVM3).",
      "Demonstrate a safe habitable orbital module with Environmental Control and Life Support Systems (ECLSS).",
      "Execute precision atmospheric re-entry, 10-parachute recovery sequence, and crew recovery operations."
    ],
    keyHighlights: [
      { label: "Target Crew Size", value: "3 Astronauts (Indian Air Force Test Pilots)" },
      { label: "Mission Duration", value: "3 Days in 400 km Orbit" },
      { label: "Launch Vehicle", value: "Human-Rated LVM3 (HLVM3)" },
      { label: "Touchdown Location", value: "Arabian Sea (Primary) / Bay of Bengal" },
      { label: "Validation Test", value: "TV-D1 In-flight Abort Test (October 2023 - Success)" },
      { label: "Robot Precursor", value: "Vyommitra (AI-Enabled Half-Humanoid Robot)" }
    ],
    payloads: [
      {
        name: "ECLSS",
        fullName: "Environmental Control & Life Support System",
        description: "Twin-redundant system managing cabin pressure (1 bar), O2/N2 gas composition, carbon dioxide scrubbing, and temperature control.",
        institution: "HSFC / VSSC"
      },
      {
        name: "CES",
        fullName: "Crew Escape System",
        description: "Solid rocket motor escape tower capable of safe extraction from launch pad up to Mach 1.2 transonic speeds.",
        institution: "VSSC, Thiruvananthapuram"
      },
      {
        name: "Vyommitra",
        fullName: "Half-Humanoid Robotics Payload",
        description: "Female-configured humanoid designed to monitor cabin environment and operate switch panels during precursor uncrewed orbital tests.",
        institution: "IISU / ISRO Centres"
      }
    ],
    trajectory: {
      type: "leo-human",
      steps: [
        { label: "HLVM3 Powered Ascent", sublabel: "Liftoff from Sriharikota Second Launch Pad into 400 km LEO", status: "planned" },
        { label: "3-Day Orbital Ops", sublabel: "Continuous microgravity biomedical and technological experiments", status: "planned" },
        { label: "De-orbit Retro-Burn", sublabel: "Service Module separation and heat-shield oriented atmospheric re-entry", status: "planned" },
        { label: "Parachute Deployment", sublabel: "10-parachute deceleration cluster down to <8.5 m/s splashdown", status: "planned" }
      ],
      conceptualNotes: "End-to-end human spaceflight safety envelope with multi-redundant abort systems."
    },
    featured: true,
    accentColor: "#E65C00"
  },
  {
    id: "spadex",
    name: "SpaDeX",
    tagline: "Space Docking Experiment — Twin Spacecraft Rendezvous Demonstration",
    category: "tech-demo",
    categoryLabel: "In-Orbit Technology",
    status: "Under Development",
    statusType: "development",
    launchDate: "Late 2024 / 2025",
    destination: "Low Earth Orbit (450 km)",
    launchVehicle: "PSLV-C60",
    orbitCoordinates: "450 km Low Earth Orbit",
    imageUrl: "/images/about-facility.jpg",
    shortDescription:
      "Twin spacecraft demonstration (Chaser and Target) to validate autonomous orbital rendezvous, physical docking, and power/data transfer.",
    fullOverview:
      "SpaDeX is an essential stepping-stone technology mission consisting of two satellites (Chaser & Target) launched simultaneously on a single PSLV. Once in orbit, the two craft will separate, drift, and autonomously rendezvous using optical laser radar (LIDAR) sensors, docking mechanisms, and interconnected power transfer.",
    primaryObjectives: [
      "Demonstrate autonomous rendezvous and physical docking of twin satellites.",
      "Validate inter-satellite power, propellant, and high-speed data transfer in microgravity.",
      "Build core capability for future Indian Space Station (Bharatiya Antariksh Station) and Lunar Sample Return."
    ],
    keyHighlights: [
      { label: "Spacecraft Pair", value: "Chaser (~220 kg) and Target (~200 kg)" },
      { label: "Launch Vehicle", value: "PSLV (Dual-Satellite Dispenser)" },
      { label: "Key Sensors", value: "Laser Range Finders, Relative GPS, Proximity Cameras" },
      { label: "Strategic Value", value: "Foundation for Bharatiya Antariksh Station (BAS)" }
    ],
    payloads: [
      {
        name: "ADS",
        fullName: "Autonomous Docking System",
        description: "Electromechanical capture latches and alignment cone for rigid spacecraft coupling in orbit.",
        institution: "URSC / VSSC"
      }
    ],
    trajectory: {
      type: "leo-docking",
      steps: [
        { label: "Dual Injection", sublabel: "Single PSLV deployment of Chaser and Target into 450 km orbit", status: "planned" },
        { label: "Separation & Drift", sublabel: "Controlled drift opening distance up to 20 kilometres", status: "planned" },
        { label: "Autonomous Rendezvous", sublabel: "Proximity sensor tracking and precise relative station-keeping", status: "planned" },
        { label: "Final Capture & Latch", sublabel: "Mechanical docking, electrical coupling, and data transfer", status: "planned" }
      ],
      conceptualNotes: "Crucial technology demonstration for human spaceflight modular habitats."
    },
    featured: false,
    accentColor: "#E65C00"
  },
  {
    id: "nisar",
    name: "NISAR",
    tagline: "NASA-ISRO Synthetic Aperture Radar — Earth Dynamic Ecosystem Mission",
    category: "earth-observation",
    categoryLabel: "Earth Observation & Radar",
    status: "Under Development",
    statusType: "development",
    launchDate: "2025",
    destination: "747 km Sun-Synchronous Polar Orbit",
    launchVehicle: "GSLV Mk II (F-Series)",
    orbitCoordinates: "747 km Sun-Synchronous Orbit, 98.4° Inclination",
    imageUrl: "/images/earth-observation.jpg",
    shortDescription:
      "World's first dual-frequency (L-band and S-band) radar satellite mapping Earth's changing ecosystems, glaciers, and fault-lines every 12 days.",
    fullOverview:
      "NISAR is a collaborative Earth observation mission between NASA (JPL) and ISRO. Utilizing a massive 12-metre deployable mesh reflector, NISAR will map the entire land and ice-covered surfaces of Earth globally with millimeter-level surface deformation precision.",
    primaryObjectives: [
      "Measure dynamic changes in Earth's ecosystems, biomass, and forest canopies.",
      "Monitor ice sheet velocities, Himalayan glacier retreats, and sea level rise indicators.",
      "Map tectonic deformations, volcanic strain buildup, and landslide hazard zones."
    ],
    keyHighlights: [
      { label: "Radar Frequencies", value: "L-band (24 cm wavelength - NASA) & S-band (9 cm - ISRO)" },
      { label: "Radar Antenna", value: "12-Metre Deployable Mesh Reflector" },
      { label: "Global Coverage", value: "Complete Earth surface scan every 12 days" },
      { label: "Spatial Resolution", value: "3 to 10 meters resolution across 240 km swath" }
    ],
    payloads: [
      {
        name: "S-SAR",
        fullName: "S-Band Synthetic Aperture Radar",
        description: "High-resolution radar optimized for coastal bathymetry, agricultural monitoring, and soil moisture.",
        institution: "SAC / ISRO, Ahmedabad"
      },
      {
        name: "L-SAR",
        fullName: "L-Band Synthetic Aperture Radar",
        description: "Deep-penetration radar mapping biomass, forest structures, ice sheet dynamics, and fault lines.",
        institution: "NASA JPL, Pasadena"
      }
    ],
    trajectory: {
      type: "leo-radar",
      steps: [
        { label: "GSLV Mk II Liftoff", sublabel: "Direct insertion into 747 km polar sun-synchronous orbit", status: "planned" },
        { label: "Antenna Boom Deployment", sublabel: "Unfurling 9-metre boom and 12-metre radar mesh reflector", status: "planned" },
        { label: "Science Radar Calibration", sublabel: "Co-aligned dual-band radar verification against ground corner targets", status: "planned" },
        { label: "Global 12-Day Survey", sublabel: "Continuous all-weather global land and cryosphere radar imaging", status: "planned" }
      ],
      conceptualNotes: "Unprecedented global radar observation enabling disaster risk assessment."
    },
    featured: false,
    accentColor: "#E65C00"
  },
  {
    id: "xposat",
    name: "XPoSat",
    tagline: "X-ray Polarimeter Satellite — Probing Cosmic High-Energy Extremes",
    category: "astrophysics",
    categoryLabel: "Space Astronomy & Astrophysics",
    status: "Operational",
    statusType: "active",
    launchDate: "01 January 2024",
    destination: "650 km Low Earth Orbit at 6° Low Inclination",
    launchVehicle: "PSLV-C58",
    orbitCoordinates: "650 km LEO, 6° Inclination",
    imageUrl: "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=1600&q=80",
    shortDescription:
      "India's first dedicated polarimetry mission to study the degree and angle of polarization of astronomical X-ray sources.",
    fullOverview:
      "XPoSat is only the world's second satellite-based X-ray polarimeter mission (alongside NASA's IXPE). It investigates complex astronomical sources such as black hole binaries, neutron stars, active galactic nuclei, and pulsar wind nebulae in the medium energy range.",
    primaryObjectives: [
      "Measure polarization of cosmic X-rays in 8-30 keV energy band from bright sources.",
      "Conduct long-term spectral and timing studies of cosmic X-ray emitters in 0.8-15 keV band."
    ],
    keyHighlights: [
      { label: "Mission Orbit", value: "650 km Circular LEO (6° low inclination)" },
      { label: "Launch Vehicle", value: "PSLV-C58 (with POEM-3 platform)" },
      { label: "Global Significance", value: "World's 2nd dedicated X-ray polarimetry space observatory" }
    ],
    payloads: [
      {
        name: "POLIX",
        fullName: "Polarimeter Instrument in X-rays",
        description: "Thomson scattering polarimeter measuring polarization parameters in 8-30 keV energy band.",
        institution: "Raman Research Institute (RRI), Bengaluru"
      },
      {
        name: "XSPECT",
        fullName: "X-ray Spectroscopy and Timing",
        description: "High-speed X-ray spectrometer observing timing variations and emission spectra in 0.8-15 keV band.",
        institution: "Space Astronomy Group, URSC, Bengaluru"
      }
    ],
    trajectory: {
      type: "leo-human",
      steps: [
        { label: "PSLV-C58 Injection", sublabel: "Placed into 650 km circular orbit at 6° inclination", status: "completed" },
        { label: "Payload Commissioning", sublabel: "High-voltage activation of POLIX xenon gas detectors", status: "completed" },
        { label: "Target Source Science", sublabel: "Continuous pointing at pulsar Crab Nebula and black hole Cygnus X-1", status: "in-progress" }
      ],
      conceptualNotes: "Dedicated astrophysical observatory operating in low Earth orbit."
    },
    featured: false,
    accentColor: "#E65C00"
  },
  {
    id: "mom",
    name: "Mangalyaan (MOM)",
    tagline: "Mars Orbiter Mission — India's Historic First Interplanetary Probe",
    category: "planetary",
    categoryLabel: "Interplanetary Exploration",
    status: "Mission Complete",
    statusType: "success",
    launchDate: "05 November 2013",
    destination: "Mars Elliptical Orbit (421 x 76,993 km)",
    launchVehicle: "PSLV-C25 (XL Configuration)",
    orbitCoordinates: "Mars Elliptical Orbit",
    imageUrl: "https://images.unsplash.com/photo-1614728423169-3f65fd722b7e?auto=format&fit=crop&w=1600&q=80",
    shortDescription:
      "Made India the first Asian nation to reach Martian orbit and the first nation in the world to succeed on its maiden attempt.",
    fullOverview:
      "The Mars Orbiter Mission (MOM), unofficially known as Mangalyaan, was India's first interplanetary mission. Launched by PSLV-C25 on November 5, 2013, it entered Martian orbit on September 24, 2014, operating for nearly 8 years (far exceeding its 6-month planned life) while mapping Martian surface features and exospheric atmospheric gases.",
    primaryObjectives: [
      "Demonstrate autonomous navigation, communication, and management during interplanetary transit.",
      "Explore Mars surface morphology, mineralogy, and exosphere using five scientific instruments."
    ],
    keyHighlights: [
      { label: "Transit Distance", value: "666 Million Kilometres" },
      { label: "Mars Orbit Insertion", value: "24 September 2014 (Maiden Attempt Success)" },
      { label: "Operational Lifetime", value: "~8 Years (Designed for 6 Months)" },
      { label: "Cost Benchmark", value: "~$74 Million (Most cost-effective Mars mission in history)" }
    ],
    payloads: [
      {
        name: "MCC",
        fullName: "Mars Colour Camera",
        description: "Captured full-disk color imagery of Mars, dust storms, and moons Phobos and Deimos.",
        institution: "SAC, Ahmedabad"
      },
      {
        name: "MSM",
        fullName: "Methane Sensor for Mars",
        description: "Measured atmospheric methane in parts per billion to search for potential biogeochemical signatures.",
        institution: "SAC, Ahmedabad"
      },
      {
        name: "TIS",
        fullName: "Thermal Infrared Imaging Spectrometer",
        description: "Measured surface thermal emissions to map composition and mineral distribution.",
        institution: "SAC, Ahmedabad"
      }
    ],
    trajectory: {
      type: "mars-insertion",
      steps: [
        { label: "PSLV-C25 Launch", sublabel: "Direct insertion into Earth parking orbit on Nov 5, 2013", status: "completed" },
        { label: "Trans-Mars Injection", sublabel: "Dec 1, 2013 escape burn sending probe onto heliocentric hyperbolic cruise", status: "completed" },
        { label: "300-Day Cruise", sublabel: "666 million km interplanetary navigation with mid-course corrections", status: "completed" },
        { label: "Mars Orbit Insertion", sublabel: "Sept 24, 2014 main 440N liquid engine retro-burn into Martian orbit", status: "completed" }
      ],
      conceptualNotes: "Historic interplanetary benchmark completed on first attempt."
    },
    featured: false,
    accentColor: "#E65C00"
  }
];
